name: Quit
favicon: null
layout_spectrum: 0.7813097394537181
typography_spectrum: 0.7931793215684593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.018011369509622455
  lightness: 0.8550631038378924
  saturation: 0.6783835515379906
  rhythmicContrast: 0.3408874503802508
purpose: []
